version: 1
services:
  - type: web
    name: my-python-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    instanceType: "standard"
    region: "us"
